services:
  backend:
    build:
      context: ./timease-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./timease-backend:/app
      - /app/target
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=timease-db
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
    depends_on:
      - db

  frontend:
    build:
      context: ./timease-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./timease-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: timease-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
